//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswareTable
    {
        public long Id { get; set; }
        public Nullable<long> QusID { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> CorrectAns { get; set; }
        public byte[] Image { get; set; }
        public string Remarks { get; set; }
        public string ProjectFilePath { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
    
        public virtual QuestionTable QuestionTable { get; set; }
    }
}
