//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionTable()
        {
            this.AnswareTables = new HashSet<AnswareTable>();
        }
    
        public long QusID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Question { get; set; }
        public string Type { get; set; }
        public string Subject { get; set; }
        public byte[] Image { get; set; }
        public string Tag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswareTable> AnswareTables { get; set; }
    }
}
