//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_Credential
    {
        public long Id { get; set; }
        public string user_Name { get; set; }
        public string user_passWord { get; set; }
        public string user_FirstName { get; set; }
        public string User_LastName { get; set; }
        public string user_email { get; set; }
        public string user_registered_Date { get; set; }
        public Nullable<bool> Activity { get; set; }
        public string display_name { get; set; }
        public byte[] User_Image { get; set; }
        public string User_Address { get; set; }
        public string User_Country { get; set; }
        public Nullable<int> User_PostalCode { get; set; }
        public string User_Abouts { get; set; }
        public byte[] SALT { get; set; }
        public string HASH { get; set; }
    }
}
